spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop003:3306/user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true

## hbase config
hbase:
  rootdir: hdfs://node01:8020/hbase
  zookeeper:
    quorum: hadoop001,hadoop002,hadoop003
  client:
    scanner:
      timeout:
        period: 100000
  rpc:
    timeout: 10000

## redis config
redis:
  host: 10.20.0.92
  port: 6379
  db: 0

## kafka config
kafka:
  bootstrap:
    servers: hadoop002:9092
  zookeeper:
    connect: 10.20.0.92:2181

## data path
rating:
  data:
    path= ratings.csv