spring:
  datasource:
    username: root
    password: 136501412
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop003/recommend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      storage_engine: innodb
      format_sql: true
  hbase:
    master: hadoop001:16010
    quorum: hadoop001:2181,hadoop002:2181,hadoop003:2181
    root-dir: hdfs://hadoop001:9000/hbase
    znode-parent: /hbase
    client-port: 2181
    session-timeout: 60000
    rpc-timeout: 60000
    operation-timeout: 30000
    scanner-timeout: 200000
    ssl-enabled: false
    distributed: true
  kafka:
    bootstrap-servers: 10.20.0.92:9092
    consumer:
      group-id: recommender
      auto-offset-reset: latest
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: recommender
      username:
      password: