spring:
  kafka:
    bootstrap-servers: 10.20.0.92:9092
    consumer:
      group-id: recommender
      auto-offset-reset: latest
      enable-auto-commit: false
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: recommender
      username: root
      password: '123456'