kafka:
  #  bootstrap-servers: kafka-cp-kafka-headless:9092
  bootstrap-servers: 10.20.0.92:9092

security:
  auth:
    enabled: true

spring:
  kafka:
    producer:
      bootstrap-servers: 10.20.0.92:9092