server:
  port: 6800

spring:
  application:
    name: "@artifactId@"
  profiles:
    active: "@activatedProfile@"
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  mvc:
    static-path-pattern: /static/** # js ,css 等静态文件路径