server:
  port: 6800

security:
  auth:
    enabled: false

transactionsRateDisplayLimit: 50

kafka:
  topic:
    transactions: topic-detect-livetransactions
    rules: topic-detect-rules
    alerts: topic-detect-alerts
    latency: topic-detect-latency
    current-rules: topic-detect-current-rules
  listeners:
    transactions.id: transactions-listener

  bootstrap-servers: localhost:9092

web-socket:
  topic:
    transactions: /topic/transactions
    alerts: /topic/alerts
    latency: /topic/latency

management:
  endpoints:
    web:
      exposure:
        include: mappings, loggers

spring:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer